from enum import Enum


class QRTagType(str, Enum):
    HOUSEHOLD = "HOUSEHOLD"
    BULK_GENERATOR = "BULK_GENERATOR"
    GENERIC = "GENERIC"


class AssignedEntityType(str, Enum):
    HOUSEHOLD = "HOUSEHOLD"
    BULK_GENERATOR = "BULK_GENERATOR"


class DwellingType(str, Enum):
    APARTMENT = "APARTMENT"
    INDEPENDENT_HOUSE = "INDEPENDENT_HOUSE"
    SLUM = "SLUM"
    GATED_COMMUNITY = "GATED_COMMUNITY"
    OTHER = "OTHER"


class OnboardingStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"


class GeneratorType(str, Enum):
    HOTEL = "HOTEL"
    RESTAURANT = "RESTAURANT"
    MARKET = "MARKET"
    INSTITUTION = "INSTITUTION"
    HOSPITAL = "HOSPITAL"
    INDUSTRY = "INDUSTRY"
    COMMERCIAL_COMPLEX = "COMMERCIAL_COMPLEX"
    OTHER = "OTHER"


class ComplianceStatus(str, Enum):
    COMPLIANT = "COMPLIANT"
    NON_COMPLIANT = "NON_COMPLIANT"
    UNDER_REVIEW = "UNDER_REVIEW"


class EmploymentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ON_LEAVE = "ON_LEAVE"
    INACTIVE = "INACTIVE"
    TERMINATED = "TERMINATED"


class VehicleType(str, Enum):
    AUTO_TIPPER = "AUTO_TIPPER"
    COMPACTOR = "COMPACTOR"
    TRUCK = "TRUCK"
    E_RICKSHAW = "E_RICKSHAW"
    TRACTOR = "TRACTOR"
    OTHER = "OTHER"


class OwnershipType(str, Enum):
    MUNICIPAL = "MUNICIPAL"
    CONTRACTOR = "CONTRACTOR"
    PPP = "PPP"
    OTHER = "OTHER"


class RouteType(str, Enum):
    DOOR_TO_DOOR = "DOOR_TO_DOOR"
    BULK_COLLECTION = "BULK_COLLECTION"
    SPECIAL_DRIVE = "SPECIAL_DRIVE"
    TRANSFER = "TRANSFER"


class OperationalSourceType(str, Enum):
    HOUSEHOLD = "HOUSEHOLD"
    BULK_GENERATOR = "BULK_GENERATOR"


class PickupStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    MISSED = "MISSED"
    CANCELLED = "CANCELLED"


class WasteCategory(str, Enum):
    WET = "WET"
    DRY = "DRY"
    MIXED = "MIXED"
    SANITARY = "SANITARY"
    DOMESTIC_HAZARDOUS = "DOMESTIC_HAZARDOUS"
    CND = "CND"
    OTHER = "OTHER"


class PickupEventType(str, Enum):
    TASK_CREATED = "TASK_CREATED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_MISSED = "TASK_MISSED"
    LOCATION_PING = "LOCATION_PING"
    WEIGHT_CAPTURED = "WEIGHT_CAPTURED"
    PHOTO_CAPTURED = "PHOTO_CAPTURED"
    NOTE_ADDED = "NOTE_ADDED"


class FacilityType(str, Enum):
    MRF = "MRF"
    COMPOST_PLANT = "COMPOST_PLANT"
    BIOMETHANATION = "BIOMETHANATION"
    RDF_PLANT = "RDF_PLANT"
    WTE = "WTE"
    TRANSFER_STATION = "TRANSFER_STATION"
    LANDFILL = "LANDFILL"
    OTHER = "OTHER"


class BatchStatus(str, Enum):
    CREATED = "CREATED"
    IN_TRANSIT = "IN_TRANSIT"
    RECEIVED = "RECEIVED"
    PROCESSING = "PROCESSING"
    PROCESSED = "PROCESSED"
    PARTIALLY_DISPOSED = "PARTIALLY_DISPOSED"
    CLOSED = "CLOSED"


class TransferEntityType(str, Enum):
    ROUTE = "ROUTE"
    SHIFT = "SHIFT"
    COLLECTION_POINT = "COLLECTION_POINT"
    FACILITY = "FACILITY"
    OTHER = "OTHER"


class TransferStatus(str, Enum):
    DISPATCHED = "DISPATCHED"
    IN_TRANSIT = "IN_TRANSIT"
    RECEIVED = "RECEIVED"
    CANCELLED = "CANCELLED"


class VerificationStatus(str, Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    REJECTED = "REJECTED"


class ProcessType(str, Enum):
    SEGREGATION = "SEGREGATION"
    COMPOSTING = "COMPOSTING"
    BIOMETHANATION = "BIOMETHANATION"
    RECYCLING = "RECYCLING"
    RDF = "RDF"
    WTE = "WTE"
    OTHER = "OTHER"


class ProcessingStatus(str, Enum):
    INITIATED = "INITIATED"
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    REJECTED = "REJECTED"


class DisposalMethod(str, Enum):
    LANDFILL = "LANDFILL"
    CONTROLLED_DUMP = "CONTROLLED_DUMP"
    INCINERATION = "INCINERATION"
    CO_PROCESSING = "CO_PROCESSING"
    OTHER = "OTHER"


class WasteType(str, Enum):
    MIXED_MSW = "MIXED_MSW"
    ORGANIC = "ORGANIC"
    PLASTIC = "PLASTIC"
    METAL = "METAL"
    PAPER = "PAPER"
    GLASS = "GLASS"
    CND = "CND"
    SANITARY = "SANITARY"
    OTHER = "OTHER"


class RecoveryMethod(str, Enum):
    RECYCLING = "RECYCLING"
    COMPOSTING = "COMPOSTING"
    BIOMETHANATION = "BIOMETHANATION"
    RDF = "RDF"
    ENERGY_RECOVERY = "ENERGY_RECOVERY"
    CO_PROCESSING = "CO_PROCESSING"
    OTHER = "OTHER"


class CarbonProjectType(str, Enum):
    CITY_WIDE_DIVERSION = "CITY_WIDE_DIVERSION"
    METHANE_AVOIDANCE = "METHANE_AVOIDANCE"
    RECYCLING_ENHANCEMENT = "RECYCLING_ENHANCEMENT"
    COMPOSTING_PROGRAM = "COMPOSTING_PROGRAM"
    ENERGY_RECOVERY_PROGRAM = "ENERGY_RECOVERY_PROGRAM"
    OTHER = "OTHER"


class CarbonProjectStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    COMPLETED = "COMPLETED"
    CLOSED = "CLOSED"


class CarbonEventType(str, Enum):
    LANDFILL_EMISSION = "LANDFILL_EMISSION"
    PROCESSING_EMISSION = "PROCESSING_EMISSION"
    RECYCLING_AVOIDED = "RECYCLING_AVOIDED"
    COMPOSTING_AVOIDED = "COMPOSTING_AVOIDED"
    RECOVERY_AVOIDED = "RECOVERY_AVOIDED"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"


class CarbonCalculationStatus(str, Enum):
    PENDING = "PENDING"
    CALCULATED = "CALCULATED"
    MANUAL = "MANUAL"
    FAILED = "FAILED"


class CarbonSourceEntityType(str, Enum):
    BATCH = "BATCH"
    FACILITY = "FACILITY"
    PROCESSING_RECORD = "PROCESSING_RECORD"
    LANDFILL_RECORD = "LANDFILL_RECORD"
    RECOVERY_CERTIFICATE = "RECOVERY_CERTIFICATE"
    OTHER = "OTHER"


class LedgerEntryType(str, Enum):
    EMISSION = "EMISSION"
    AVOIDED_EMISSION = "AVOIDED_EMISSION"
    NET_ADJUSTMENT = "NET_ADJUSTMENT"


class DebitCreditDirection(str, Enum):
    DEBIT = "DEBIT"
    CREDIT = "CREDIT"


class SummaryStatus(str, Enum):
    DRAFT = "DRAFT"
    GENERATED = "GENERATED"
    VERIFIED = "VERIFIED"
    FINALIZED = "FINALIZED"
