from app.db.mixins import Base
from app.models import (
    address,
    bulk_waste_generator,
    carbon_event,
    carbon_ledger_entry,
    carbon_project,
    carbon_verification,
    city,
    collected_batch,
    emission_factor,
    environmental_summary,
    facility_receipt,
    household,
    landfill_record,
    organization,
    pickup_log,
    pickup_task,
    processing_facility,
    processing_record,
    qr_code_tag,
    recovery_certificate,
    role,
    route,
    route_stop,
    shift,
    transfer_record,
    user,
    user_role,
    vehicle,
    ward,
    worker_profile,
    zone,
)

__all__ = ["Base"]
