import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { StatusBadge } from "@/components/ui-extensions/status-badge";
import { formatDateTime } from "@/lib/utils";
import type { ExportHistoryRecord } from "@/types/audit";

export function ExportHistoryTable({ rows }: { rows: ExportHistoryRecord[] }) {
  if (!rows.length) {
    return <p className="text-sm text-slate-500">No exports generated yet.</p>;
  }

  return (
    <div className="rounded-md border border-slate-200 bg-white">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>Export ID</TableHead>
            <TableHead>Type</TableHead>
            <TableHead>Generated By</TableHead>
            <TableHead>Timestamp</TableHead>
            <TableHead>Status</TableHead>
            <TableHead>Download</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {rows.map((row) => (
            <TableRow key={row.id}>
              <TableCell className="font-mono text-xs">{row.id}</TableCell>
              <TableCell>{row.export_type}</TableCell>
              <TableCell>{row.generated_by}</TableCell>
              <TableCell>{formatDateTime(row.timestamp)}</TableCell>
              <TableCell><StatusBadge value={row.status} /></TableCell>
              <TableCell>{row.download_link ? <a href={row.download_link} className="text-emerald-700 hover:underline">Download</a> : <span className="text-slate-400">Local file</span>}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  );
}
