"""add processing recovery disposal lifecycle

Revision ID: 20949dc23286
Revises: 755e1f6a94cd
Create Date: 2026-03-13 18:58:24.353722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20949dc23286'
down_revision: Union[str, Sequence[str], None] = '755e1f6a94cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_facilities',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('facility_code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('facility_type', sa.Enum('MRF', 'COMPOST_PLANT', 'BIOMETHANATION', 'RDF_PLANT', 'WTE', 'TRANSFER_STATION', 'LANDFILL', 'OTHER', name='facility_type', native_enum=False), nullable=False),
    sa.Column('operator_name', sa.String(length=220), nullable=True),
    sa.Column('license_number', sa.String(length=120), nullable=True),
    sa.Column('capacity_kg_per_day', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processing_facilities_city_id', 'processing_facilities', ['city_id'], unique=False)
    op.create_index(op.f('ix_processing_facilities_created_by'), 'processing_facilities', ['created_by'], unique=False)
    op.create_index('ix_processing_facilities_facility_code', 'processing_facilities', ['facility_code'], unique=True)
    op.create_index('ix_processing_facilities_facility_type', 'processing_facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_processing_facilities_updated_by'), 'processing_facilities', ['updated_by'], unique=False)
    op.create_index('ix_processing_facilities_ward_id', 'processing_facilities', ['ward_id'], unique=False)
    op.create_index('ix_processing_facilities_zone_id', 'processing_facilities', ['zone_id'], unique=False)
    op.create_table('collected_batches',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.UUID(), nullable=True),
    sa.Column('assigned_worker_id', sa.UUID(), nullable=True),
    sa.Column('origin_route_id', sa.UUID(), nullable=True),
    sa.Column('batch_code', sa.String(length=80), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('source_type_summary', sa.String(length=150), nullable=True),
    sa.Column('total_weight_kg', sa.Float(), nullable=True),
    sa.Column('batch_status', sa.Enum('CREATED', 'IN_TRANSIT', 'RECEIVED', 'PROCESSING', 'PROCESSED', 'PARTIALLY_DISPOSED', 'CLOSED', name='batch_status', native_enum=False), server_default='CREATED', nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['worker_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['origin_route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collected_batches_batch_code', 'collected_batches', ['batch_code'], unique=True)
    op.create_index('ix_collected_batches_batch_status', 'collected_batches', ['batch_status'], unique=False)
    op.create_index('ix_collected_batches_city_id', 'collected_batches', ['city_id'], unique=False)
    op.create_index(op.f('ix_collected_batches_created_by'), 'collected_batches', ['created_by'], unique=False)
    op.create_index('ix_collected_batches_created_date', 'collected_batches', ['created_date'], unique=False)
    op.create_index(op.f('ix_collected_batches_updated_by'), 'collected_batches', ['updated_by'], unique=False)
    op.create_index('ix_collected_batches_ward_id', 'collected_batches', ['ward_id'], unique=False)
    op.create_index('ix_collected_batches_zone_id', 'collected_batches', ['zone_id'], unique=False)
    op.create_table('landfill_records',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('transported_by_vehicle_id', sa.UUID(), nullable=True),
    sa.Column('disposal_date', sa.Date(), nullable=False),
    sa.Column('waste_weight_kg', sa.Float(), nullable=False),
    sa.Column('disposal_method', sa.Enum('LANDFILL', 'CONTROLLED_DUMP', 'INCINERATION', 'CO_PROCESSING', 'OTHER', name='disposal_method', native_enum=False), nullable=False),
    sa.Column('landfill_cell', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['collected_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['processing_facilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transported_by_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_landfill_records_batch_id', 'landfill_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_landfill_records_created_by'), 'landfill_records', ['created_by'], unique=False)
    op.create_index('ix_landfill_records_disposal_date', 'landfill_records', ['disposal_date'], unique=False)
    op.create_index('ix_landfill_records_disposal_method', 'landfill_records', ['disposal_method'], unique=False)
    op.create_index('ix_landfill_records_facility_id', 'landfill_records', ['facility_id'], unique=False)
    op.create_index(op.f('ix_landfill_records_updated_by'), 'landfill_records', ['updated_by'], unique=False)
    op.create_table('processing_records',
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('process_type', sa.Enum('SEGREGATION', 'COMPOSTING', 'BIOMETHANATION', 'RECYCLING', 'RDF', 'WTE', 'OTHER', name='process_type', native_enum=False), nullable=False),
    sa.Column('input_weight_kg', sa.Float(), nullable=False),
    sa.Column('output_recovered_kg', sa.Float(), nullable=True),
    sa.Column('output_rejected_kg', sa.Float(), nullable=True),
    sa.Column('residue_to_landfill_kg', sa.Float(), nullable=True),
    sa.Column('organic_compost_kg', sa.Float(), nullable=True),
    sa.Column('recyclable_plastic_kg', sa.Float(), nullable=True),
    sa.Column('recyclable_metal_kg', sa.Float(), nullable=True),
    sa.Column('recyclable_paper_kg', sa.Float(), nullable=True),
    sa.Column('recyclable_glass_kg', sa.Float(), nullable=True),
    sa.Column('energy_recovered_kwh', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.Enum('INITIATED', 'COMPLETED', 'PARTIAL', 'REJECTED', name='processing_status', native_enum=False), server_default='INITIATED', nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['collected_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['facility_id'], ['processing_facilities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_processing_records_batch_id', 'processing_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_processing_records_created_by'), 'processing_records', ['created_by'], unique=False)
    op.create_index('ix_processing_records_facility_id', 'processing_records', ['facility_id'], unique=False)
    op.create_index('ix_processing_records_process_type', 'processing_records', ['process_type'], unique=False)
    op.create_index('ix_processing_records_processed_at', 'processing_records', ['processed_at'], unique=False)
    op.create_index('ix_processing_records_processing_status', 'processing_records', ['processing_status'], unique=False)
    op.create_index(op.f('ix_processing_records_updated_by'), 'processing_records', ['updated_by'], unique=False)
    op.create_table('recovery_certificates',
    sa.Column('certificate_number', sa.String(length=120), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('bulk_generator_id', sa.UUID(), nullable=True),
    sa.Column('issued_by_user_id', sa.UUID(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('waste_type', sa.Enum('MIXED_MSW', 'ORGANIC', 'PLASTIC', 'METAL', 'PAPER', 'GLASS', 'CND', 'SANITARY', 'OTHER', name='waste_type', native_enum=False), nullable=False),
    sa.Column('certified_weight_kg', sa.Float(), nullable=False),
    sa.Column('recovery_method', sa.Enum('RECYCLING', 'COMPOSTING', 'BIOMETHANATION', 'RDF', 'ENERGY_RECOVERY', 'CO_PROCESSING', 'OTHER', name='recovery_method', native_enum=False), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verification_status', native_enum=False), server_default='PENDING', nullable=False),
    sa.Column('certificate_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['collected_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bulk_generator_id'], ['bulk_waste_generators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['processing_facilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recovery_certificates_batch_id', 'recovery_certificates', ['batch_id'], unique=False)
    op.create_index('ix_recovery_certificates_bulk_generator_id', 'recovery_certificates', ['bulk_generator_id'], unique=False)
    op.create_index('ix_recovery_certificates_certificate_number', 'recovery_certificates', ['certificate_number'], unique=True)
    op.create_index(op.f('ix_recovery_certificates_created_by'), 'recovery_certificates', ['created_by'], unique=False)
    op.create_index('ix_recovery_certificates_facility_id', 'recovery_certificates', ['facility_id'], unique=False)
    op.create_index(op.f('ix_recovery_certificates_updated_by'), 'recovery_certificates', ['updated_by'], unique=False)
    op.create_index('ix_recovery_certificates_verification_status', 'recovery_certificates', ['verification_status'], unique=False)
    op.create_index('ix_recovery_certificates_waste_type', 'recovery_certificates', ['waste_type'], unique=False)
    op.create_table('transfer_records',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('from_entity_type', sa.Enum('ROUTE', 'SHIFT', 'COLLECTION_POINT', 'FACILITY', 'OTHER', name='transfer_entity_type', native_enum=False), nullable=False),
    sa.Column('from_entity_id', sa.UUID(), nullable=True),
    sa.Column('to_facility_id', sa.UUID(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('dispatched_weight_kg', sa.Float(), nullable=False),
    sa.Column('received_weight_kg', sa.Float(), nullable=True),
    sa.Column('transfer_status', sa.Enum('DISPATCHED', 'IN_TRANSIT', 'RECEIVED', 'CANCELLED', name='transfer_status', native_enum=False), server_default='DISPATCHED', nullable=False),
    sa.Column('manifest_number', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['collected_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_facility_id'], ['processing_facilities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transfer_records_batch_id', 'transfer_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_transfer_records_created_by'), 'transfer_records', ['created_by'], unique=False)
    op.create_index('ix_transfer_records_dispatched_at', 'transfer_records', ['dispatched_at'], unique=False)
    op.create_index('ix_transfer_records_to_facility_id', 'transfer_records', ['to_facility_id'], unique=False)
    op.create_index('ix_transfer_records_transfer_status', 'transfer_records', ['transfer_status'], unique=False)
    op.create_index(op.f('ix_transfer_records_updated_by'), 'transfer_records', ['updated_by'], unique=False)
    op.create_table('facility_receipts',
    sa.Column('transfer_record_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('received_by_user_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('gross_weight_kg', sa.Float(), nullable=True),
    sa.Column('net_weight_kg', sa.Float(), nullable=False),
    sa.Column('contamination_notes', sa.String(length=1000), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verification_status', native_enum=False), server_default='PENDING', nullable=False),
    sa.Column('proof_document_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['processing_facilities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transfer_record_id'], ['transfer_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_receipts_created_by'), 'facility_receipts', ['created_by'], unique=False)
    op.create_index('ix_facility_receipts_facility_id', 'facility_receipts', ['facility_id'], unique=False)
    op.create_index('ix_facility_receipts_transfer_record_id', 'facility_receipts', ['transfer_record_id'], unique=True)
    op.create_index(op.f('ix_facility_receipts_updated_by'), 'facility_receipts', ['updated_by'], unique=False)
    op.create_index('ix_facility_receipts_verification_status', 'facility_receipts', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_facility_receipts_verification_status', table_name='facility_receipts')
    op.drop_index(op.f('ix_facility_receipts_updated_by'), table_name='facility_receipts')
    op.drop_index('ix_facility_receipts_transfer_record_id', table_name='facility_receipts')
    op.drop_index('ix_facility_receipts_facility_id', table_name='facility_receipts')
    op.drop_index(op.f('ix_facility_receipts_created_by'), table_name='facility_receipts')
    op.drop_table('facility_receipts')
    op.drop_index(op.f('ix_transfer_records_updated_by'), table_name='transfer_records')
    op.drop_index('ix_transfer_records_transfer_status', table_name='transfer_records')
    op.drop_index('ix_transfer_records_to_facility_id', table_name='transfer_records')
    op.drop_index('ix_transfer_records_dispatched_at', table_name='transfer_records')
    op.drop_index(op.f('ix_transfer_records_created_by'), table_name='transfer_records')
    op.drop_index('ix_transfer_records_batch_id', table_name='transfer_records')
    op.drop_table('transfer_records')
    op.drop_index('ix_recovery_certificates_waste_type', table_name='recovery_certificates')
    op.drop_index('ix_recovery_certificates_verification_status', table_name='recovery_certificates')
    op.drop_index(op.f('ix_recovery_certificates_updated_by'), table_name='recovery_certificates')
    op.drop_index('ix_recovery_certificates_facility_id', table_name='recovery_certificates')
    op.drop_index(op.f('ix_recovery_certificates_created_by'), table_name='recovery_certificates')
    op.drop_index('ix_recovery_certificates_certificate_number', table_name='recovery_certificates')
    op.drop_index('ix_recovery_certificates_bulk_generator_id', table_name='recovery_certificates')
    op.drop_index('ix_recovery_certificates_batch_id', table_name='recovery_certificates')
    op.drop_table('recovery_certificates')
    op.drop_index(op.f('ix_processing_records_updated_by'), table_name='processing_records')
    op.drop_index('ix_processing_records_processing_status', table_name='processing_records')
    op.drop_index('ix_processing_records_processed_at', table_name='processing_records')
    op.drop_index('ix_processing_records_process_type', table_name='processing_records')
    op.drop_index('ix_processing_records_facility_id', table_name='processing_records')
    op.drop_index(op.f('ix_processing_records_created_by'), table_name='processing_records')
    op.drop_index('ix_processing_records_batch_id', table_name='processing_records')
    op.drop_table('processing_records')
    op.drop_index(op.f('ix_landfill_records_updated_by'), table_name='landfill_records')
    op.drop_index('ix_landfill_records_facility_id', table_name='landfill_records')
    op.drop_index('ix_landfill_records_disposal_method', table_name='landfill_records')
    op.drop_index('ix_landfill_records_disposal_date', table_name='landfill_records')
    op.drop_index(op.f('ix_landfill_records_created_by'), table_name='landfill_records')
    op.drop_index('ix_landfill_records_batch_id', table_name='landfill_records')
    op.drop_table('landfill_records')
    op.drop_index('ix_collected_batches_zone_id', table_name='collected_batches')
    op.drop_index('ix_collected_batches_ward_id', table_name='collected_batches')
    op.drop_index(op.f('ix_collected_batches_updated_by'), table_name='collected_batches')
    op.drop_index('ix_collected_batches_created_date', table_name='collected_batches')
    op.drop_index(op.f('ix_collected_batches_created_by'), table_name='collected_batches')
    op.drop_index('ix_collected_batches_city_id', table_name='collected_batches')
    op.drop_index('ix_collected_batches_batch_status', table_name='collected_batches')
    op.drop_index('ix_collected_batches_batch_code', table_name='collected_batches')
    op.drop_table('collected_batches')
    op.drop_index('ix_processing_facilities_zone_id', table_name='processing_facilities')
    op.drop_index('ix_processing_facilities_ward_id', table_name='processing_facilities')
    op.drop_index(op.f('ix_processing_facilities_updated_by'), table_name='processing_facilities')
    op.drop_index('ix_processing_facilities_facility_type', table_name='processing_facilities')
    op.drop_index('ix_processing_facilities_facility_code', table_name='processing_facilities')
    op.drop_index(op.f('ix_processing_facilities_created_by'), table_name='processing_facilities')
    op.drop_index('ix_processing_facilities_city_id', table_name='processing_facilities')
    op.drop_table('processing_facilities')
    # ### end Alembic commands ###
