"""add worker operations and pickup lifecycle

Revision ID: 755e1f6a94cd
Revises: 7643c86df746
Create Date: 2026-03-13 18:38:25.162298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755e1f6a94cd'
down_revision: Union[str, Sequence[str], None] = '7643c86df746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('route_code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('route_type', sa.Enum('DOOR_TO_DOOR', 'BULK_COLLECTION', 'SPECIAL_DRIVE', 'TRANSFER', name='route_type', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routes_city_id', 'routes', ['city_id'], unique=False)
    op.create_index(op.f('ix_routes_created_by'), 'routes', ['created_by'], unique=False)
    op.create_index('ix_routes_route_code', 'routes', ['route_code'], unique=True)
    op.create_index('ix_routes_route_type', 'routes', ['route_type'], unique=False)
    op.create_index(op.f('ix_routes_updated_by'), 'routes', ['updated_by'], unique=False)
    op.create_index('ix_routes_ward_id', 'routes', ['ward_id'], unique=False)
    op.create_index('ix_routes_zone_id', 'routes', ['zone_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('registration_number', sa.String(length=60), nullable=False),
    sa.Column('vehicle_type', sa.Enum('AUTO_TIPPER', 'COMPACTOR', 'TRUCK', 'E_RICKSHAW', 'TRACTOR', 'OTHER', name='vehicle_type', native_enum=False), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('ownership_type', sa.Enum('MUNICIPAL', 'CONTRACTOR', 'PPP', 'OTHER', name='ownership_type', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicles_city_id', 'vehicles', ['city_id'], unique=False)
    op.create_index(op.f('ix_vehicles_created_by'), 'vehicles', ['created_by'], unique=False)
    op.create_index('ix_vehicles_ownership_type', 'vehicles', ['ownership_type'], unique=False)
    op.create_index('ix_vehicles_registration_number', 'vehicles', ['registration_number'], unique=True)
    op.create_index(op.f('ix_vehicles_updated_by'), 'vehicles', ['updated_by'], unique=False)
    op.create_index('ix_vehicles_vehicle_type', 'vehicles', ['vehicle_type'], unique=False)
    op.create_index('ix_vehicles_ward_id', 'vehicles', ['ward_id'], unique=False)
    op.create_index('ix_vehicles_zone_id', 'vehicles', ['zone_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('HOUSEHOLD', 'BULK_GENERATOR', name='operational_source_type', native_enum=False), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('bulk_generator_id', sa.UUID(), nullable=True),
    sa.Column('expected_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('((household_id IS NOT NULL)::int + (bulk_generator_id IS NOT NULL)::int) = 1', name='ck_route_stops_exactly_one_source'),
    sa.ForeignKeyConstraint(['bulk_generator_id'], ['bulk_waste_generators.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'bulk_generator_id', name='uq_route_stops_route_id_bulk_generator_id'),
    sa.UniqueConstraint('route_id', 'household_id', name='uq_route_stops_route_id_household_id'),
    sa.UniqueConstraint('route_id', 'stop_sequence', name='uq_route_stops_route_id_stop_sequence')
    )
    op.create_index('ix_route_stops_bulk_generator_id', 'route_stops', ['bulk_generator_id'], unique=False)
    op.create_index(op.f('ix_route_stops_created_by'), 'route_stops', ['created_by'], unique=False)
    op.create_index('ix_route_stops_household_id', 'route_stops', ['household_id'], unique=False)
    op.create_index('ix_route_stops_route_id', 'route_stops', ['route_id'], unique=False)
    op.create_index('ix_route_stops_source_type', 'route_stops', ['source_type'], unique=False)
    op.create_index(op.f('ix_route_stops_updated_by'), 'route_stops', ['updated_by'], unique=False)
    op.create_table('shifts',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('supervisor_user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supervisor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shifts_city_id', 'shifts', ['city_id'], unique=False)
    op.create_index(op.f('ix_shifts_created_by'), 'shifts', ['created_by'], unique=False)
    op.create_index('ix_shifts_shift_date', 'shifts', ['shift_date'], unique=False)
    op.create_index('ix_shifts_supervisor_user_id', 'shifts', ['supervisor_user_id'], unique=False)
    op.create_index(op.f('ix_shifts_updated_by'), 'shifts', ['updated_by'], unique=False)
    op.create_index('ix_shifts_ward_id', 'shifts', ['ward_id'], unique=False)
    op.create_index('ix_shifts_zone_id', 'shifts', ['zone_id'], unique=False)
    op.create_table('worker_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('employee_code', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=False),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'ON_LEAVE', 'INACTIVE', 'TERMINATED', name='employment_status', native_enum=False), server_default='ACTIVE', nullable=False),
    sa.Column('joined_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_worker_profiles_city_id', 'worker_profiles', ['city_id'], unique=False)
    op.create_index(op.f('ix_worker_profiles_created_by'), 'worker_profiles', ['created_by'], unique=False)
    op.create_index('ix_worker_profiles_employee_code', 'worker_profiles', ['employee_code'], unique=True)
    op.create_index('ix_worker_profiles_employment_status', 'worker_profiles', ['employment_status'], unique=False)
    op.create_index(op.f('ix_worker_profiles_updated_by'), 'worker_profiles', ['updated_by'], unique=False)
    op.create_index('ix_worker_profiles_user_id', 'worker_profiles', ['user_id'], unique=True)
    op.create_index('ix_worker_profiles_ward_id', 'worker_profiles', ['ward_id'], unique=False)
    op.create_index('ix_worker_profiles_zone_id', 'worker_profiles', ['zone_id'], unique=False)
    op.create_table('pickup_tasks',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('route_stop_id', sa.UUID(), nullable=True),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.Enum('HOUSEHOLD', 'BULK_GENERATOR', name='operational_source_type', native_enum=False), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('bulk_generator_id', sa.UUID(), nullable=True),
    sa.Column('assigned_worker_id', sa.UUID(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time_window_start', sa.Time(), nullable=True),
    sa.Column('scheduled_time_window_end', sa.Time(), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(), nullable=True),
    sa.Column('actual_completed_at', sa.DateTime(), nullable=True),
    sa.Column('pickup_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'MISSED', 'CANCELLED', name='pickup_status', native_enum=False), server_default='PENDING', nullable=False),
    sa.Column('waste_category', sa.Enum('WET', 'DRY', 'MIXED', 'SANITARY', 'DOMESTIC_HAZARDOUS', 'CND', 'OTHER', name='waste_category', native_enum=False), nullable=True),
    sa.Column('expected_weight_kg', sa.Float(), nullable=True),
    sa.Column('actual_weight_kg', sa.Float(), nullable=True),
    sa.Column('contamination_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('proof_photo_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('((household_id IS NOT NULL)::int + (bulk_generator_id IS NOT NULL)::int) = 1', name='ck_pickup_tasks_exactly_one_source'),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['worker_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bulk_generator_id'], ['bulk_waste_generators.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_stop_id'], ['route_stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pickup_tasks_assigned_vehicle_id', 'pickup_tasks', ['assigned_vehicle_id'], unique=False)
    op.create_index('ix_pickup_tasks_assigned_worker_id', 'pickup_tasks', ['assigned_worker_id'], unique=False)
    op.create_index('ix_pickup_tasks_city_id', 'pickup_tasks', ['city_id'], unique=False)
    op.create_index(op.f('ix_pickup_tasks_created_by'), 'pickup_tasks', ['created_by'], unique=False)
    op.create_index('ix_pickup_tasks_pickup_status', 'pickup_tasks', ['pickup_status'], unique=False)
    op.create_index('ix_pickup_tasks_route_id', 'pickup_tasks', ['route_id'], unique=False)
    op.create_index('ix_pickup_tasks_route_stop_id', 'pickup_tasks', ['route_stop_id'], unique=False)
    op.create_index('ix_pickup_tasks_scheduled_date', 'pickup_tasks', ['scheduled_date'], unique=False)
    op.create_index('ix_pickup_tasks_shift_id', 'pickup_tasks', ['shift_id'], unique=False)
    op.create_index('ix_pickup_tasks_source_type', 'pickup_tasks', ['source_type'], unique=False)
    op.create_index(op.f('ix_pickup_tasks_updated_by'), 'pickup_tasks', ['updated_by'], unique=False)
    op.create_index('ix_pickup_tasks_ward_id', 'pickup_tasks', ['ward_id'], unique=False)
    op.create_index('ix_pickup_tasks_zone_id', 'pickup_tasks', ['zone_id'], unique=False)
    op.create_table('pickup_logs',
    sa.Column('pickup_task_id', sa.UUID(), nullable=False),
    sa.Column('worker_profile_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('TASK_CREATED', 'TASK_ASSIGNED', 'TASK_STARTED', 'TASK_COMPLETED', 'TASK_MISSED', 'LOCATION_PING', 'WEIGHT_CAPTURED', 'PHOTO_CAPTURED', 'NOTE_ADDED', name='pickup_event_type', native_enum=False), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('event_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['pickup_task_id'], ['pickup_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_profile_id'], ['worker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_logs_created_by'), 'pickup_logs', ['created_by'], unique=False)
    op.create_index('ix_pickup_logs_event_at', 'pickup_logs', ['event_at'], unique=False)
    op.create_index('ix_pickup_logs_event_type', 'pickup_logs', ['event_type'], unique=False)
    op.create_index('ix_pickup_logs_pickup_task_id', 'pickup_logs', ['pickup_task_id'], unique=False)
    op.create_index(op.f('ix_pickup_logs_updated_by'), 'pickup_logs', ['updated_by'], unique=False)
    op.create_index('ix_pickup_logs_worker_profile_id', 'pickup_logs', ['worker_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pickup_logs_worker_profile_id', table_name='pickup_logs')
    op.drop_index(op.f('ix_pickup_logs_updated_by'), table_name='pickup_logs')
    op.drop_index('ix_pickup_logs_pickup_task_id', table_name='pickup_logs')
    op.drop_index('ix_pickup_logs_event_type', table_name='pickup_logs')
    op.drop_index('ix_pickup_logs_event_at', table_name='pickup_logs')
    op.drop_index(op.f('ix_pickup_logs_created_by'), table_name='pickup_logs')
    op.drop_table('pickup_logs')
    op.drop_index('ix_pickup_tasks_zone_id', table_name='pickup_tasks')
    op.drop_index('ix_pickup_tasks_ward_id', table_name='pickup_tasks')
    op.drop_index(op.f('ix_pickup_tasks_updated_by'), table_name='pickup_tasks')
    op.drop_index('ix_pickup_tasks_source_type', table_name='pickup_tasks')
    op.drop_index('ix_pickup_tasks_shift_id', table_name='pickup_tasks')
    op.drop_index('ix_pickup_tasks_scheduled_date', table_name='pickup_tasks')
    op.drop_index('ix_pickup_tasks_route_stop_id', table_name='pickup_tasks')
    op.drop_index('ix_pickup_tasks_route_id', table_name='pickup_tasks')
    op.drop_index('ix_pickup_tasks_pickup_status', table_name='pickup_tasks')
    op.drop_index(op.f('ix_pickup_tasks_created_by'), table_name='pickup_tasks')
    op.drop_index('ix_pickup_tasks_city_id', table_name='pickup_tasks')
    op.drop_index('ix_pickup_tasks_assigned_worker_id', table_name='pickup_tasks')
    op.drop_index('ix_pickup_tasks_assigned_vehicle_id', table_name='pickup_tasks')
    op.drop_table('pickup_tasks')
    op.drop_index('ix_worker_profiles_zone_id', table_name='worker_profiles')
    op.drop_index('ix_worker_profiles_ward_id', table_name='worker_profiles')
    op.drop_index('ix_worker_profiles_user_id', table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_updated_by'), table_name='worker_profiles')
    op.drop_index('ix_worker_profiles_employment_status', table_name='worker_profiles')
    op.drop_index('ix_worker_profiles_employee_code', table_name='worker_profiles')
    op.drop_index(op.f('ix_worker_profiles_created_by'), table_name='worker_profiles')
    op.drop_index('ix_worker_profiles_city_id', table_name='worker_profiles')
    op.drop_table('worker_profiles')
    op.drop_index('ix_shifts_zone_id', table_name='shifts')
    op.drop_index('ix_shifts_ward_id', table_name='shifts')
    op.drop_index(op.f('ix_shifts_updated_by'), table_name='shifts')
    op.drop_index('ix_shifts_supervisor_user_id', table_name='shifts')
    op.drop_index('ix_shifts_shift_date', table_name='shifts')
    op.drop_index(op.f('ix_shifts_created_by'), table_name='shifts')
    op.drop_index('ix_shifts_city_id', table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_route_stops_updated_by'), table_name='route_stops')
    op.drop_index('ix_route_stops_source_type', table_name='route_stops')
    op.drop_index('ix_route_stops_route_id', table_name='route_stops')
    op.drop_index('ix_route_stops_household_id', table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_created_by'), table_name='route_stops')
    op.drop_index('ix_route_stops_bulk_generator_id', table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index('ix_vehicles_zone_id', table_name='vehicles')
    op.drop_index('ix_vehicles_ward_id', table_name='vehicles')
    op.drop_index('ix_vehicles_vehicle_type', table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_updated_by'), table_name='vehicles')
    op.drop_index('ix_vehicles_registration_number', table_name='vehicles')
    op.drop_index('ix_vehicles_ownership_type', table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_created_by'), table_name='vehicles')
    op.drop_index('ix_vehicles_city_id', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_routes_zone_id', table_name='routes')
    op.drop_index('ix_routes_ward_id', table_name='routes')
    op.drop_index(op.f('ix_routes_updated_by'), table_name='routes')
    op.drop_index('ix_routes_route_type', table_name='routes')
    op.drop_index('ix_routes_route_code', table_name='routes')
    op.drop_index(op.f('ix_routes_created_by'), table_name='routes')
    op.drop_index('ix_routes_city_id', table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
