"""add source registry foundation

Revision ID: 7643c86df746
Revises: 93fa9f493c3c
Create Date: 2026-03-13 17:46:40.905589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7643c86df746'
down_revision: Union[str, Sequence[str], None] = '93fa9f493c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=150), nullable=False),
    sa.Column('city_name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_addresses_city_name', 'addresses', ['city_name'], unique=False)
    op.create_index(op.f('ix_addresses_created_by'), 'addresses', ['created_by'], unique=False)
    op.create_index('ix_addresses_postal_code', 'addresses', ['postal_code'], unique=False)
    op.create_index(op.f('ix_addresses_updated_by'), 'addresses', ['updated_by'], unique=False)
    op.create_table('qr_code_tags',
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('tag_type', sa.Enum('HOUSEHOLD', 'BULK_GENERATOR', 'GENERIC', name='qr_tag_type', native_enum=False), nullable=False),
    sa.Column('assigned_entity_type', sa.Enum('HOUSEHOLD', 'BULK_GENERATOR', name='assigned_entity_type', native_enum=False), nullable=True),
    sa.Column('assigned_entity_id', sa.UUID(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qr_code_tags_assigned_entity', 'qr_code_tags', ['assigned_entity_type', 'assigned_entity_id'], unique=False)
    op.create_index('ix_qr_code_tags_code', 'qr_code_tags', ['code'], unique=True)
    op.create_index(op.f('ix_qr_code_tags_created_by'), 'qr_code_tags', ['created_by'], unique=False)
    op.create_index(op.f('ix_qr_code_tags_updated_by'), 'qr_code_tags', ['updated_by'], unique=False)
    op.create_table('bulk_waste_generators',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('qr_tag_id', sa.UUID(), nullable=True),
    sa.Column('generator_code', sa.String(length=120), nullable=False),
    sa.Column('entity_name', sa.String(length=220), nullable=False),
    sa.Column('contact_person_name', sa.String(length=200), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('generator_type', sa.Enum('HOTEL', 'RESTAURANT', 'MARKET', 'INSTITUTION', 'HOSPITAL', 'INDUSTRY', 'COMMERCIAL_COMPLEX', 'OTHER', name='generator_type', native_enum=False), nullable=False),
    sa.Column('estimated_daily_waste_kg', sa.Float(), nullable=True),
    sa.Column('compliance_status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'UNDER_REVIEW', name='compliance_status', native_enum=False), server_default='UNDER_REVIEW', nullable=False),
    sa.Column('onboarding_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='onboarding_status', native_enum=False), server_default='PENDING', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qr_tag_id'], ['qr_code_tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bulk_generators_city_id', 'bulk_waste_generators', ['city_id'], unique=False)
    op.create_index('ix_bulk_generators_generator_code', 'bulk_waste_generators', ['generator_code'], unique=True)
    op.create_index('ix_bulk_generators_qr_tag_id', 'bulk_waste_generators', ['qr_tag_id'], unique=True)
    op.create_index('ix_bulk_generators_ward_id', 'bulk_waste_generators', ['ward_id'], unique=False)
    op.create_index('ix_bulk_generators_zone_id', 'bulk_waste_generators', ['zone_id'], unique=False)
    op.create_index(op.f('ix_bulk_waste_generators_created_by'), 'bulk_waste_generators', ['created_by'], unique=False)
    op.create_index(op.f('ix_bulk_waste_generators_updated_by'), 'bulk_waste_generators', ['updated_by'], unique=False)
    op.create_table('households',
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('qr_tag_id', sa.UUID(), nullable=True),
    sa.Column('household_code', sa.String(length=120), nullable=False),
    sa.Column('household_head_name', sa.String(length=200), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('number_of_members', sa.Integer(), nullable=True),
    sa.Column('dwelling_type', sa.Enum('APARTMENT', 'INDEPENDENT_HOUSE', 'SLUM', 'GATED_COMMUNITY', 'OTHER', name='dwelling_type', native_enum=False), nullable=True),
    sa.Column('onboarding_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='onboarding_status', native_enum=False), server_default='PENDING', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['qr_tag_id'], ['qr_code_tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_households_city_id', 'households', ['city_id'], unique=False)
    op.create_index(op.f('ix_households_created_by'), 'households', ['created_by'], unique=False)
    op.create_index('ix_households_household_code', 'households', ['household_code'], unique=True)
    op.create_index('ix_households_qr_tag_id', 'households', ['qr_tag_id'], unique=True)
    op.create_index(op.f('ix_households_updated_by'), 'households', ['updated_by'], unique=False)
    op.create_index('ix_households_ward_id', 'households', ['ward_id'], unique=False)
    op.create_index('ix_households_zone_id', 'households', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_households_zone_id', table_name='households')
    op.drop_index('ix_households_ward_id', table_name='households')
    op.drop_index(op.f('ix_households_updated_by'), table_name='households')
    op.drop_index('ix_households_qr_tag_id', table_name='households')
    op.drop_index('ix_households_household_code', table_name='households')
    op.drop_index(op.f('ix_households_created_by'), table_name='households')
    op.drop_index('ix_households_city_id', table_name='households')
    op.drop_table('households')
    op.drop_index(op.f('ix_bulk_waste_generators_updated_by'), table_name='bulk_waste_generators')
    op.drop_index(op.f('ix_bulk_waste_generators_created_by'), table_name='bulk_waste_generators')
    op.drop_index('ix_bulk_generators_zone_id', table_name='bulk_waste_generators')
    op.drop_index('ix_bulk_generators_ward_id', table_name='bulk_waste_generators')
    op.drop_index('ix_bulk_generators_qr_tag_id', table_name='bulk_waste_generators')
    op.drop_index('ix_bulk_generators_generator_code', table_name='bulk_waste_generators')
    op.drop_index('ix_bulk_generators_city_id', table_name='bulk_waste_generators')
    op.drop_table('bulk_waste_generators')
    op.drop_index(op.f('ix_qr_code_tags_updated_by'), table_name='qr_code_tags')
    op.drop_index(op.f('ix_qr_code_tags_created_by'), table_name='qr_code_tags')
    op.drop_index('ix_qr_code_tags_code', table_name='qr_code_tags')
    op.drop_index('ix_qr_code_tags_assigned_entity', table_name='qr_code_tags')
    op.drop_table('qr_code_tags')
    op.drop_index(op.f('ix_addresses_updated_by'), table_name='addresses')
    op.drop_index('ix_addresses_postal_code', table_name='addresses')
    op.drop_index(op.f('ix_addresses_created_by'), table_name='addresses')
    op.drop_index('ix_addresses_city_name', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
