"""add carbon accounting and environmental ledger

Revision ID: 8c863b30a53a
Revises: 20949dc23286
Create Date: 2026-03-13 19:16:49.632280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c863b30a53a'
down_revision: Union[str, Sequence[str], None] = '20949dc23286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('factor_code', sa.String(length=80), nullable=False),
    sa.Column('factor_name', sa.String(length=220), nullable=False),
    sa.Column('waste_type', sa.Enum('MIXED_MSW', 'ORGANIC', 'PLASTIC', 'METAL', 'PAPER', 'GLASS', 'CND', 'SANITARY', 'OTHER', name='waste_type', native_enum=False), nullable=False),
    sa.Column('process_type', sa.Enum('SEGREGATION', 'COMPOSTING', 'BIOMETHANATION', 'RECYCLING', 'RDF', 'WTE', 'OTHER', name='process_type', native_enum=False), nullable=True),
    sa.Column('factor_unit', sa.String(length=80), nullable=False),
    sa.Column('factor_value', sa.Float(), nullable=False),
    sa.Column('source_standard', sa.String(length=220), nullable=True),
    sa.Column('geography', sa.String(length=220), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('methodology_reference', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_factors_created_by'), 'emission_factors', ['created_by'], unique=False)
    op.create_index('ix_emission_factors_effective_from', 'emission_factors', ['effective_from'], unique=False)
    op.create_index('ix_emission_factors_effective_to', 'emission_factors', ['effective_to'], unique=False)
    op.create_index('ix_emission_factors_factor_code', 'emission_factors', ['factor_code'], unique=True)
    op.create_index('ix_emission_factors_process_type', 'emission_factors', ['process_type'], unique=False)
    op.create_index(op.f('ix_emission_factors_updated_by'), 'emission_factors', ['updated_by'], unique=False)
    op.create_index('ix_emission_factors_waste_type', 'emission_factors', ['waste_type'], unique=False)
    op.create_table('carbon_projects',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('project_code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('project_type', sa.Enum('CITY_WIDE_DIVERSION', 'METHANE_AVOIDANCE', 'RECYCLING_ENHANCEMENT', 'COMPOSTING_PROGRAM', 'ENERGY_RECOVERY_PROGRAM', 'OTHER', name='carbon_project_type', native_enum=False), nullable=False),
    sa.Column('methodology_name', sa.String(length=220), nullable=False),
    sa.Column('methodology_version', sa.String(length=120), nullable=True),
    sa.Column('standard_body', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CLOSED', name='carbon_project_status', native_enum=False), server_default='DRAFT', nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_carbon_projects_city_id', 'carbon_projects', ['city_id'], unique=False)
    op.create_index(op.f('ix_carbon_projects_created_by'), 'carbon_projects', ['created_by'], unique=False)
    op.create_index('ix_carbon_projects_project_code', 'carbon_projects', ['project_code'], unique=True)
    op.create_index('ix_carbon_projects_project_type', 'carbon_projects', ['project_type'], unique=False)
    op.create_index('ix_carbon_projects_status', 'carbon_projects', ['status'], unique=False)
    op.create_index(op.f('ix_carbon_projects_updated_by'), 'carbon_projects', ['updated_by'], unique=False)
    op.create_index('ix_carbon_projects_ward_id', 'carbon_projects', ['ward_id'], unique=False)
    op.create_table('environmental_summaries',
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('reporting_month', sa.Integer(), nullable=False),
    sa.Column('reporting_year', sa.Integer(), nullable=False),
    sa.Column('total_collected_kg', sa.Float(), nullable=True),
    sa.Column('total_processed_kg', sa.Float(), nullable=True),
    sa.Column('total_recycled_kg', sa.Float(), nullable=True),
    sa.Column('total_composted_kg', sa.Float(), nullable=True),
    sa.Column('total_landfilled_kg', sa.Float(), nullable=True),
    sa.Column('landfill_diversion_percent', sa.Float(), nullable=True),
    sa.Column('gross_emission_kgco2e', sa.Float(), nullable=True),
    sa.Column('avoided_emission_kgco2e', sa.Float(), nullable=True),
    sa.Column('net_emission_kgco2e', sa.Float(), nullable=True),
    sa.Column('summary_status', sa.Enum('DRAFT', 'GENERATED', 'VERIFIED', 'FINALIZED', name='summary_status', native_enum=False), server_default='GENERATED', nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'ward_id', 'reporting_month', 'reporting_year', name='uq_environmental_summaries_city_ward_month_year')
    )
    op.create_index('ix_environmental_summaries_city_id', 'environmental_summaries', ['city_id'], unique=False)
    op.create_index(op.f('ix_environmental_summaries_created_by'), 'environmental_summaries', ['created_by'], unique=False)
    op.create_index('ix_environmental_summaries_period', 'environmental_summaries', ['reporting_year', 'reporting_month'], unique=False)
    op.create_index('ix_environmental_summaries_summary_status', 'environmental_summaries', ['summary_status'], unique=False)
    op.create_index(op.f('ix_environmental_summaries_updated_by'), 'environmental_summaries', ['updated_by'], unique=False)
    op.create_index('ix_environmental_summaries_ward_id', 'environmental_summaries', ['ward_id'], unique=False)
    op.create_table('carbon_events',
    sa.Column('carbon_project_id', sa.UUID(), nullable=True),
    sa.Column('event_code', sa.String(length=100), nullable=False),
    sa.Column('source_entity_type', sa.Enum('BATCH', 'FACILITY', 'PROCESSING_RECORD', 'LANDFILL_RECORD', 'RECOVERY_CERTIFICATE', 'OTHER', name='carbon_source_entity_type', native_enum=False), nullable=False),
    sa.Column('source_entity_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('facility_id', sa.UUID(), nullable=True),
    sa.Column('processing_record_id', sa.UUID(), nullable=True),
    sa.Column('landfill_record_id', sa.UUID(), nullable=True),
    sa.Column('recovery_certificate_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('LANDFILL_EMISSION', 'PROCESSING_EMISSION', 'RECYCLING_AVOIDED', 'COMPOSTING_AVOIDED', 'RECOVERY_AVOIDED', 'MANUAL_ADJUSTMENT', name='carbon_event_type', native_enum=False), nullable=False),
    sa.Column('waste_type', sa.Enum('MIXED_MSW', 'ORGANIC', 'PLASTIC', 'METAL', 'PAPER', 'GLASS', 'CND', 'SANITARY', 'OTHER', name='waste_type', native_enum=False), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('factor_id', sa.UUID(), nullable=True),
    sa.Column('factor_value', sa.Float(), nullable=True),
    sa.Column('gross_emission_kgco2e', sa.Float(), nullable=True),
    sa.Column('avoided_emission_kgco2e', sa.Float(), nullable=True),
    sa.Column('net_emission_kgco2e', sa.Float(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('methodology_snapshot', sa.String(length=1000), nullable=True),
    sa.Column('calculation_status', sa.Enum('PENDING', 'CALCULATED', 'MANUAL', 'FAILED', name='carbon_calculation_status', native_enum=False), server_default='PENDING', nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['collected_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['carbon_project_id'], ['carbon_projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['processing_facilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['factor_id'], ['emission_factors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['landfill_record_id'], ['landfill_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processing_record_id'], ['processing_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovery_certificate_id'], ['recovery_certificates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_carbon_events_batch_id', 'carbon_events', ['batch_id'], unique=False)
    op.create_index('ix_carbon_events_calculation_status', 'carbon_events', ['calculation_status'], unique=False)
    op.create_index(op.f('ix_carbon_events_created_by'), 'carbon_events', ['created_by'], unique=False)
    op.create_index('ix_carbon_events_event_code', 'carbon_events', ['event_code'], unique=True)
    op.create_index('ix_carbon_events_event_date', 'carbon_events', ['event_date'], unique=False)
    op.create_index('ix_carbon_events_event_type', 'carbon_events', ['event_type'], unique=False)
    op.create_index('ix_carbon_events_facility_id', 'carbon_events', ['facility_id'], unique=False)
    op.create_index(op.f('ix_carbon_events_updated_by'), 'carbon_events', ['updated_by'], unique=False)
    op.create_index('ix_carbon_events_waste_type', 'carbon_events', ['waste_type'], unique=False)
    op.create_table('carbon_ledger_entries',
    sa.Column('ledger_entry_code', sa.String(length=100), nullable=False),
    sa.Column('carbon_event_id', sa.UUID(), nullable=False),
    sa.Column('entry_type', sa.Enum('EMISSION', 'AVOIDED_EMISSION', 'NET_ADJUSTMENT', name='ledger_entry_type', native_enum=False), nullable=False),
    sa.Column('debit_credit_direction', sa.Enum('DEBIT', 'CREDIT', name='debit_credit_direction', native_enum=False), nullable=False),
    sa.Column('quantity_kgco2e', sa.Float(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('ward_id', sa.UUID(), nullable=True),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verification_status', native_enum=False), server_default='PENDING', nullable=False),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['carbon_event_id'], ['carbon_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_carbon_ledger_entries_carbon_event_id', 'carbon_ledger_entries', ['carbon_event_id'], unique=False)
    op.create_index('ix_carbon_ledger_entries_city_id', 'carbon_ledger_entries', ['city_id'], unique=False)
    op.create_index(op.f('ix_carbon_ledger_entries_created_by'), 'carbon_ledger_entries', ['created_by'], unique=False)
    op.create_index('ix_carbon_ledger_entries_entry_type', 'carbon_ledger_entries', ['entry_type'], unique=False)
    op.create_index('ix_carbon_ledger_entries_ledger_entry_code', 'carbon_ledger_entries', ['ledger_entry_code'], unique=True)
    op.create_index('ix_carbon_ledger_entries_period', 'carbon_ledger_entries', ['period_year', 'period_month'], unique=False)
    op.create_index(op.f('ix_carbon_ledger_entries_updated_by'), 'carbon_ledger_entries', ['updated_by'], unique=False)
    op.create_index('ix_carbon_ledger_entries_verification_status', 'carbon_ledger_entries', ['verification_status'], unique=False)
    op.create_index('ix_carbon_ledger_entries_ward_id', 'carbon_ledger_entries', ['ward_id'], unique=False)
    op.create_table('carbon_verifications',
    sa.Column('carbon_event_id', sa.UUID(), nullable=True),
    sa.Column('ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verification_status', native_enum=False), server_default='PENDING', nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('evidence_document_url', sa.String(length=1000), nullable=True),
    sa.Column('discrepancy_notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('((carbon_event_id IS NOT NULL)::int + (ledger_entry_id IS NOT NULL)::int) >= 1', name='ck_carbon_verifications_at_least_one_target'),
    sa.ForeignKeyConstraint(['carbon_event_id'], ['carbon_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['carbon_ledger_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_carbon_verifications_carbon_event_id', 'carbon_verifications', ['carbon_event_id'], unique=False)
    op.create_index(op.f('ix_carbon_verifications_created_by'), 'carbon_verifications', ['created_by'], unique=False)
    op.create_index('ix_carbon_verifications_ledger_entry_id', 'carbon_verifications', ['ledger_entry_id'], unique=False)
    op.create_index(op.f('ix_carbon_verifications_updated_by'), 'carbon_verifications', ['updated_by'], unique=False)
    op.create_index('ix_carbon_verifications_verification_status', 'carbon_verifications', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_carbon_verifications_verification_status', table_name='carbon_verifications')
    op.drop_index(op.f('ix_carbon_verifications_updated_by'), table_name='carbon_verifications')
    op.drop_index('ix_carbon_verifications_ledger_entry_id', table_name='carbon_verifications')
    op.drop_index(op.f('ix_carbon_verifications_created_by'), table_name='carbon_verifications')
    op.drop_index('ix_carbon_verifications_carbon_event_id', table_name='carbon_verifications')
    op.drop_table('carbon_verifications')
    op.drop_index('ix_carbon_ledger_entries_ward_id', table_name='carbon_ledger_entries')
    op.drop_index('ix_carbon_ledger_entries_verification_status', table_name='carbon_ledger_entries')
    op.drop_index(op.f('ix_carbon_ledger_entries_updated_by'), table_name='carbon_ledger_entries')
    op.drop_index('ix_carbon_ledger_entries_period', table_name='carbon_ledger_entries')
    op.drop_index('ix_carbon_ledger_entries_ledger_entry_code', table_name='carbon_ledger_entries')
    op.drop_index('ix_carbon_ledger_entries_entry_type', table_name='carbon_ledger_entries')
    op.drop_index(op.f('ix_carbon_ledger_entries_created_by'), table_name='carbon_ledger_entries')
    op.drop_index('ix_carbon_ledger_entries_city_id', table_name='carbon_ledger_entries')
    op.drop_index('ix_carbon_ledger_entries_carbon_event_id', table_name='carbon_ledger_entries')
    op.drop_table('carbon_ledger_entries')
    op.drop_index('ix_carbon_events_waste_type', table_name='carbon_events')
    op.drop_index(op.f('ix_carbon_events_updated_by'), table_name='carbon_events')
    op.drop_index('ix_carbon_events_facility_id', table_name='carbon_events')
    op.drop_index('ix_carbon_events_event_type', table_name='carbon_events')
    op.drop_index('ix_carbon_events_event_date', table_name='carbon_events')
    op.drop_index('ix_carbon_events_event_code', table_name='carbon_events')
    op.drop_index(op.f('ix_carbon_events_created_by'), table_name='carbon_events')
    op.drop_index('ix_carbon_events_calculation_status', table_name='carbon_events')
    op.drop_index('ix_carbon_events_batch_id', table_name='carbon_events')
    op.drop_table('carbon_events')
    op.drop_index('ix_environmental_summaries_ward_id', table_name='environmental_summaries')
    op.drop_index(op.f('ix_environmental_summaries_updated_by'), table_name='environmental_summaries')
    op.drop_index('ix_environmental_summaries_summary_status', table_name='environmental_summaries')
    op.drop_index('ix_environmental_summaries_period', table_name='environmental_summaries')
    op.drop_index(op.f('ix_environmental_summaries_created_by'), table_name='environmental_summaries')
    op.drop_index('ix_environmental_summaries_city_id', table_name='environmental_summaries')
    op.drop_table('environmental_summaries')
    op.drop_index('ix_carbon_projects_ward_id', table_name='carbon_projects')
    op.drop_index(op.f('ix_carbon_projects_updated_by'), table_name='carbon_projects')
    op.drop_index('ix_carbon_projects_status', table_name='carbon_projects')
    op.drop_index('ix_carbon_projects_project_type', table_name='carbon_projects')
    op.drop_index('ix_carbon_projects_project_code', table_name='carbon_projects')
    op.drop_index(op.f('ix_carbon_projects_created_by'), table_name='carbon_projects')
    op.drop_index('ix_carbon_projects_city_id', table_name='carbon_projects')
    op.drop_table('carbon_projects')
    op.drop_index('ix_emission_factors_waste_type', table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_updated_by'), table_name='emission_factors')
    op.drop_index('ix_emission_factors_process_type', table_name='emission_factors')
    op.drop_index('ix_emission_factors_factor_code', table_name='emission_factors')
    op.drop_index('ix_emission_factors_effective_to', table_name='emission_factors')
    op.drop_index('ix_emission_factors_effective_from', table_name='emission_factors')
    op.drop_index(op.f('ix_emission_factors_created_by'), table_name='emission_factors')
    op.drop_table('emission_factors')
    # ### end Alembic commands ###
