export const BOOLEAN_OPTIONS = [
  { label: "Active", value: "true" },
  { label: "Inactive", value: "false" },
];

export const ROLE_CODE_OPTIONS = [
  "SUPER_ADMIN",
  "CITY_ADMIN",
  "WARD_OFFICER",
  "SANITATION_SUPERVISOR",
  "WORKER",
  "CITIZEN",
  "BULK_GENERATOR",
  "PROCESSOR",
  "AUDITOR",
];

export const DWELLING_TYPES = ["APARTMENT", "INDEPENDENT_HOUSE", "SLUM", "GATED_COMMUNITY", "OTHER"];
export const ONBOARDING_STATUSES = ["PENDING", "IN_PROGRESS", "COMPLETED", "REJECTED"];
export const GENERATOR_TYPES = ["HOTEL", "RESTAURANT", "MARKET", "INSTITUTION", "HOSPITAL", "INDUSTRY", "COMMERCIAL_COMPLEX", "OTHER"];
export const COMPLIANCE_STATUSES = ["COMPLIANT", "NON_COMPLIANT", "UNDER_REVIEW"];
export const EMPLOYMENT_STATUSES = ["ACTIVE", "ON_LEAVE", "INACTIVE", "TERMINATED"];
export const VEHICLE_TYPES = ["AUTO_TIPPER", "COMPACTOR", "TRUCK", "E_RICKSHAW", "TRACTOR", "OTHER"];
export const OWNERSHIP_TYPES = ["MUNICIPAL", "CONTRACTOR", "PPP", "OTHER"];
export const ROUTE_TYPES = ["DOOR_TO_DOOR", "BULK_COLLECTION", "SPECIAL_DRIVE", "TRANSFER"];
export const SOURCE_TYPES = ["HOUSEHOLD", "BULK_GENERATOR"];
export const PICKUP_STATUSES = ["PENDING", "IN_PROGRESS", "COMPLETED", "MISSED", "CANCELLED"];
export const WASTE_CATEGORIES = ["WET", "DRY", "MIXED", "SANITARY", "DOMESTIC_HAZARDOUS", "CND", "OTHER"];
export const FACILITY_TYPES = ["MRF", "COMPOST_PLANT", "BIOMETHANATION", "RDF_PLANT", "WTE", "TRANSFER_STATION", "LANDFILL", "OTHER"];
export const PICKUP_EVENT_TYPES = ["TASK_CREATED", "TASK_ASSIGNED", "TASK_STARTED", "TASK_COMPLETED", "TASK_MISSED", "LOCATION_PING", "WEIGHT_CAPTURED", "PHOTO_CAPTURED", "NOTE_ADDED"];
export const BATCH_STATUSES = ["CREATED", "IN_TRANSIT", "RECEIVED", "PROCESSING", "PROCESSED", "PARTIALLY_DISPOSED", "CLOSED"];
export const TRANSFER_ENTITY_TYPES = ["ROUTE", "SHIFT", "COLLECTION_POINT", "FACILITY", "OTHER"];
export const TRANSFER_STATUSES = ["DISPATCHED", "IN_TRANSIT", "RECEIVED", "CANCELLED"];
export const VERIFICATION_STATUSES = ["PENDING", "VERIFIED", "REJECTED"];
export const PROCESS_TYPES = ["SEGREGATION", "COMPOSTING", "BIOMETHANATION", "RECYCLING", "RDF", "WTE", "OTHER"];
export const PROCESSING_STATUSES = ["INITIATED", "COMPLETED", "PARTIAL", "REJECTED"];
export const DISPOSAL_METHODS = ["LANDFILL", "CONTROLLED_DUMP", "INCINERATION", "CO_PROCESSING", "OTHER"];
export const WASTE_TYPES = ["MIXED_MSW", "ORGANIC", "PLASTIC", "METAL", "PAPER", "GLASS", "CND", "SANITARY", "OTHER"];
export const RECOVERY_METHODS = ["RECYCLING", "COMPOSTING", "BIOMETHANATION", "RDF", "ENERGY_RECOVERY", "CO_PROCESSING", "OTHER"];
